name: Set up
description: Set up pnpm and node
runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
