name: Push to main

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  ci:
    name: Build
    uses: './.github/workflows/ci-build.yml'

  cd:
    name: Deploy
    needs: ci
    uses: './.github/workflows/cd-pages.yml'
